[package]
name = "advent-of-code-rust"
edition = "2021"
version = "0.1.0"
authors = ["thefreeman42 <adamturczi@gmail.com>"]

[dependencies]
dotenv = "0.15.0"
itertools = "0.13.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
